version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'WeCare'
      MYSQL_USER: 'ryednap'
      MYSQL_PASSWORD: 'unico'
      MYSQL_ROOT_PASSWORD: 'ultimo'
    ports:
      - '3306:3306'
    expose:
      # open port 3306 open the container
      - '3306'
    #data gets deleted after container exits or breaks specify the location to persist
    volumes:
      - mysql:/var/lib/mysql

  mysql_auth:
   container_name: mysql_auth
   image: mysql:5.7
   restart: unless-stopped
   environment:
     MYSQL_DATABASE: 'WeCare'
     MYSQL_USER: 'ryednap'
     MYSQL_PASSWORD: 'unico'
     MYSQL_ROOT_PASSWORD: 'ultimo'

   hostname: auth_database
   ports:
     - '4022:4022'
   expose:
       # open port 4022 open the container
       - '4022'
     #data gets deleted after container exits or breaks specify the location to persist
   volumes:
       - mysql:/var/lib/mysql_auth

volumes:
  mysql:
    driver: local
  mysql_auth:
    driver: local
